version: 2.1

orbs:
  node: circleci/node@4.5.1
jobs:
  test:
   executor: node/default
   steps:
    - checkout
    - run: | 
        npm i  -g react-scripts
        
      
  build:
    docker:
      - image: cimg/node:12.0.0
    steps:
      - run: docker --version


    

workflows:
  version: 2
  Test-Build-Publish-Deploy:
    jobs:
      - test
      - build:
         requires:
           - test